### PR TITLE
[Code health] Migrate to built-in Kotlin

### LINKED ISSUE #3539: [Code health] Migrate to built-in Kotlin
After upgrading gradle to 9.0 (https://github.com/google/ground-android/pull/3538), we started seeing a warning to migrate kotlin android plugin to built-in kotlin support.

https://developer.android.com/build/migrate-to-built-in-kotlin

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #3539

### Summary
Migrate project to built-in Kotlin support in AGP 9.0 and remove kapt dependency.

### Changes Done

- **Build Configuration:**
  - Enabled built-in Kotlin support by removing `android.builtInKotlin=false` in `gradle.properties`.
  - Removed `kotlin-android` plugin application from `app/build.gradle`, `e2eTest/build.gradle`, root `build.gradle`, and `libs.versions.toml`.
  - Removed `kotlin-kapt` plugin from `app/build.gradle`.
- **Refactoring:**
  - Replaced custom `app:visible` binding adapter usages with standard `android:visibility` expressions in `offline_areas_frag.xml` and `offline_area_viewer_frag.xml`.
  - Deleted `BindingAdapters.kt` as it was no longer needed after the refactoring.
- **Tests Fixes:**
  - Resolved test compilation errors by switching from `kotlin.test.Test` to `org.junit.Test` in several test files where the former failed to resolve under the new build setup.

### Advantages of this Migration

- **Simpler Build Files:** Reduces boilerplate by removing the need to explicitly apply the Kotlin plugin in every module.
- **Better Compatibility:** Avoids potential version mismatch and compatibility issues between the Android Gradle Plugin and the external Kotlin Gradle plugin.
- **Removal of Kapt:** Eliminates kapt from the build process, moving the project closer to a pure KSP and built-in setup, which helps in long-term maintainability and build performance.
- **Standardized Layouts:** Removes non-standard custom binding adapters for simple visibility toggles in favor of standard data binding expressions.

@andreia-ferreira  PTAL?

### CODE REVIEW

**Review by andreia-ferreira — APPROVED** [review]
nice! 🙌
